### ISSUE TITLE
Add ability to increase spacing (or 'blank') between symbols in toolbar 

### ISSUE THREAD

**Issue by davebhc71** [kometenstaub/customizable-page-header-buttons#17]
This is particularly critical when using on iPad, but has value on Desktop

**Comment by kometenstaub** [comment]
This is possible with CSS.

---

Individual buttons:

```css
a.view-action.page-header-button.editor\:insert-tag {
    margin-right: 2em;
}
```

![image](https://user-images.githubusercontent.com/83140328/150692927-8d982347-b4af-4b60-b916-734b67a6c46c.png)

---

For all of the buttons the plugin added:

```css
a.view-action.page-header-button {
    margin-right: 2em;
    margin-left: 1em;
}
```

![image](https://user-images.githubusercontent.com/83140328/150692938-712c4c91-36d3-4a9b-b08c-cef805a3a422.png)

---

If you want to include the ones from Obsidian as well, you can do this:

```css
a.view-action {
    margin-right: 2em !important;
}
```

![image](https://user-images.githubusercontent.com/83140328/150692947-c4bc3f86-48fb-4230-82fa-84b94fc6050d.png)

---

You can play around with the margin types/values to your liking.
